/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/charity_frontend/assets/models/Cash.glb -o src/charity_frontend/src/components/Cash.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Cash(props) {
  const { nodes, materials } = useGLTF('/models/Cash.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/models/Cash.glb')
